### ISSUE TITLE
Add anonymous (inline) scales proposal

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1088]
In some cases, graphs do not need multiple uses of the same scale.  I propose we allow anonymous scale definition directly in the `"scale"` value.  It will make the graph a bit shorter, but more importantly, it will be easier to read, because more of the relevant code will be located in one spot. I wouldn't have to jump between the scale and its only usage.

The inline scale will be identical to the named ones, except that they won't have the `name` field.  Optionally, we may consider some contextual defaults. For example, a value reference may have a field and a scale, which means that the inline scale could reuse the same field and the data source for the domain param, unless it is defined explicitly.

Adapting the [pie chart example](https://vega.github.io/vega/examples/pie-chart/):

```json
  "marks": [
    {
      "type": "arc",
      "from": {"data": "table"},
      "encode": {
        "enter": {
          "fill": {
            "scale": {"type": "ordinal", "range": {"scheme": "category20"}},
            "field": "id"
          },
```

instead of 

```json
 "scales": [
    {
      "name": "color",
      "type": "ordinal",
      "range": {"scheme": "category20"}
    }
  ],

  "marks": [
    {
      "type": "arc",
      "from": {"data": "table"},
      "encode": {
        "enter": {
          "fill": {
            "scale": "color",
            "field": "id"
          },
```

**Comment by domoritz** [comment]
I guess you could write a preprocessor that does this, right? 

Also, how do you think scales that need a domain would look like?

**Comment by nyurik** [comment]
@domoritz, I wouldn't want to compete with Vega-lite, esp when minor modifications would help :)

  The main benefit of anonymous scales, besides shorter spec, is the more manageable code. A single concept, like mark's transparency, needs to be defined in a single location. I don't have to jump between the scales and marks to make sense of the spec, or to adjust params. Right now some of the things (offset, mult) are on mark, and other part of that equation is in scales.

The domain, as well as all other scale params like `zero` can be used inline, just like you would use them inside the `scales` array. The only invalid field is the `name`.  That said, we could introduce some defaults -- e.g. if the `domain` is expected but missing, we could use the mark's data source and field.  For example, here's some code from [job voyager example](https://vega.github.io/vega/examples/job-voyager/):

```yaml
"scales": [
  {
    "name": "opacity",
    "type": "quantile",
    "range": [0, 0, 0, 0, 0, 0.1, 0.2, 0.4, 0.7, 1.0],
    "domain": {"data": "series", "field": "argmax.perc"}
  },
  {
    "name": "color",
    "type": "ordinal",
    "range": ["#33f", "#f33"],
    "domain": ["men", "women"]
  },
  {
    "name": "alpha",
    "type": "linear", "zero": true,
    "range": [0.4, 0.8],
    "domain": {"data": "series", "field": "sum"}
  }
],

"marks": [
  // top level mark
  "from": {"data": "series"},
  "fillOpacity": {"scale": "opacity", "field": "argmax.perc"},

  // group mark
  "from": { "data": "series", "facet": {...} }
     // sub-mark:
     "from": {"data": "facet"},
     "fill": {"scale": "color", "field": "sex"},
     "fillOpacity": {"scale": "alpha", "field": {"parent": "sum"}}
]
```

We could rewrite the above as:

```yaml
"marks": [
  // top level mark
  "from": {"data": "series"},
  "fillOpacity": {
    "scale": {
      "type": "quantile",
      "range": [0, 0, 0, 0, 0, 0.1, 0.2, 0.4, 0.7, 1.0],
      // The domain could be specified manually, or we could introduce rules
      // for default calculations: use field and data from context
      "domain": {"data": "series", "field": "argmax.perc"}
    },
    "field": "argmax.perc"
  },

  // group mark
  "from": { "data": "series", "facet": {...} }
    // sub-mark:
    "from": {"data": "facet"},
    "fill": {
      "scale": {
        "type": "ordinal",
        "range": ["#33f", "#f33"],
        "domain": ["men", "women"]  // domain is given, no defaults
      },
      "field": "sex"
    },
    "fillOpacity": {
      "scale": {
        "type": "linear", "zero": true,
        "range": [0.4, 0.8],
        // This is the trickiest one. Explicit domain works fine, but for defaults,
        // we could process "parent.sum" to mean that the "from" should also
        // come from the parent group mark.
        "domain": {"data": "series", "field": "sum"}
      },
      "field": {"parent": "sum"}
    }
]
```
