### ISSUE TITLE
Using scalers to get absolute values in screen coordinates

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1145]
```yaml
# Data table
    [ {val: 80}, {val: 100} ]
# Scale
    {
      name: y
      type: linear
      range: height
      domain: {data: "table", field: "val"}
    }
```
As expected, projecting any value between `[0..100]` using `y` scale gives screen coordinates of `[1000..0]` for the graph with height=1000.

How can I use the same projection if i need to calculate the thickness of a line using the original table units? Let's say I want to draw a horizontal line with thickness of a 5 in the units of the original data (0..100). If I use `scale(5)`, I get 950, whereas what I need is 50.  Is there a way to do it without doing my own math?

Thanks!
