### ISSUE TITLE
Large strokeWidth can lead to excessive bounds

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1146]
This graph draws two vertical bars, and a curve between the center points of the first and second bars (part of my [sankey graphs](https://developers.google.com/chart/interactive/docs/gallery/sankey)). In the simplest case, both bars are identical size, and the curve becomes a straight line between them. The strokeWidth of the line needs to match the vertical bar size.

This graph looks okayish with the `autosize=pad` (creates huge padding), but totally breaks down with `autosize=fit`.  Reducing strokeWidth to a smaller value hides the problem.

| autosize=pad | autosize=fit |
|---|---|
| ![image](https://user-images.githubusercontent.com/1641515/36089163-6eb6b04c-0fa8-11e8-8fc7-f6038d6a7564.png) | ![image](https://user-images.githubusercontent.com/1641515/36089182-894133c4-0fa8-11e8-851b-d4a859739ba6.png) |

(I simplified previous example to remove the side bars. The issue is still there)
```yaml
{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "width": 100,
  "height": 100,
  "autosize": "fit",     // <--------- works with "pad" somewhat
  "background": "#bbb",
  "scales": [
    {
      "name": "x",
      "type": "band",
      "range": "width",
      "domain": ["a", "b"],
      "paddingOuter": 0.05,
      "paddingInner": 0.95
    },
    {
      "name": "y",
      "type": "linear",
      "range": "height",
      "domain": [0, 100]
    }
  ],
  "data": [
    {
      "name": "edges",
      "values": [{"x1": "a", "x2": "b", "y1": 50, "y2": 50, "value": 100}],
      "transform": [
        {
          "type": "linkpath",
          "orient": "horizontal",
          "shape": {"signal": "'diagonal'"},
          "sourceY": {"expr": "scale('y', datum.y1)"},
          "sourceX": {"expr": "scale('x', datum.x1) + bandwidth('x')"},
          "targetY": {"expr": "scale('y', datum.y2)"},
          "targetX": {"expr": "scale('x', datum.x2)"}
        },
        {
          "type": "formula",
          "expr": "range('y')[0]-scale('y', datum.value)",
          "as": "strokeWidth"
        }
      ]
    }
  ],
  "axes": [
    {"orient": "bottom", "scale": "x", "zindex": 1},
    {"orient": "left", "scale": "y", "zindex": 1}
  ],
  "marks": [
    {
      "type": "path",
      "name": "edgeMark",
      "from": {"data": "edges"},
      "encode": {
        "update": {"strokeWidth": {"field": "strokeWidth"}, "path": {"field": "path"}}
      }
    }
  ]
}
```
